language: c
compiler:
    - gcc-8
before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install gcc-8
script:
    - autoreconf --install && ./configure --enable-maintainer-mode && make
